
export const auth = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
  AUTH_LOGIN_PENDING: "AUTH_LOGIN_PENDING",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_ERROR: "AUTH_LOGOUT_ERROR",
  AUTH_LOGOUT_PENDING: "AUTH_LOGOUT_PENDING",
  AUTH_AUTHORIZE_SUCCESS: "AUTH_AUTHORIZE_SUCCESS",
  AUTH_AUTHORIZE_ERROR: "AUTH_AUTHORIZE_ERROR",
  AUTH_AUTHORIZE_PENDING: "AUTH_AUTHORIZE_PENDING",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_REGISTER_ERROR: "AUTH_REGISTER_ERROR",
  AUTH_REGISTER_PENDING: "AUTH_REGISTER_PENDING",
}

export const users = {
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",
  GET_USERS_PENDING: "GET_USERS_PENDING",
}

export const avatar = {
  UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
  UPLOAD_AVATAR_ERROR: "UPLOAD_AVATAR_ERROR",
  UPLOAD_AVATAR_PENDING: "UPLOAD_AVATAR_PENDING",
}

export const updateUserSettings = {
  UPDATE_USER_SETTINGS_SUCCESS: "UPDATE_USER_SETTINGS_SUCCESS",
  UPDATE_USER_SETTINGS_ERROR: "UPDATE_USER_SETTINGS_ERROR",
  UPDATE_USER_SETTINGS_PENDING: "UPDATE_USER_SETTINGS_PENDING",
}

export const removeAvatar = {
  REMOVE_AVATAR_SUCCESS: "REMOVE_AVATAR_SUCCESS",
  REMOVE_AVATAR_ERROR: "REMOVE_AVATAR_ERROR",
  REMOVE_AVATAR_PENDING: "REMOVE_AVATAR_PENDING",
}
